apiVersion: v1
kind: Service
metadata:
  name: career-dock-service
spec:
  ports:
    - name: http
      port: 3000  # This is the port on which the service will be exposed. You can choose any available port number.
      targetPort: 3000  # This is the port on which the container is listening. It should match the containerPort defined in the Deployment.
  selector:
    app: career-dock-node # it finds the pod with this label and forwards the request to that pod
  type: LoadBalancer
